export const FAILED_REQUEST = "FAILED_REQUEST";

export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
 
export const DETAIL_REQUEST = "DETAIL_REQUEST";
export const DETAIL_SUCCESS = "DETAIL_SUCCESS";

export const DESCRIPTION_REQUEST = "DESCRIPTION_REQUEST";
export const DESCRIPTION_SUCCESS = "DESCRIPTION_SUCCESS";