export const SET_REQUESTING = "SET_REQUESTING"
export const FAILED_REQUEST = "FAILED_REQUEST";

export const UPDATE_SEARCH_TEXT = "UPDATE_SEARCH_TEXT"
 
export const BREADCRUMB_REQUEST = "BREADCRUMB_REQUEST";
export const BREADCRUMB_SUCCESS = "BREADCRUMB_SUCCESS";